# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='master',
            name='year',
        ),
        migrations.AddField(
            model_name='master',
            name='year_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='year_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Category'),
        ),
    ]
