# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20160504_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='tag',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='master',
            name='year_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='year_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
