# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20160504_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='last',
            field=models.BooleanField(default=True),
        ),
    ]
